name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Optional: You can check Docker version and info
    steps:
      - name: Check Docker version
        run: docker --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t anshultaklikar/docker-react -f Dockerfile.dev .

      - name: Run tests inside Docker container
        run: docker run -e CI=true anshultaklikar/docker-react npm run test