name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t anshultaklikar/docker-react -f Dockerfile.dev .

      # Step 3: Run Docker container to execute tests
      - name: Run tests inside Docker container
        run: docker run --rm anshultaklikar/docker-react npm run test -- --coverage --watchAll=false
=======
    # Optional: You can check Docker version and info
    steps:
      - name: Check Docker version
        run: docker --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t anshultaklikar/docker-react -f Dockerfile.dev .

      - name: Run tests inside Docker container
        run: docker run -e CI=true anshultaklikar/docker-react npm run test -- --coverage

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: MyApplicationName
          environment_name: MyApplication-Environment
          version_label: ${{ github.sha }}
          existing_bucket_name: MyBucketName
          region: us-west-2
          deployment_package: deploy.zip
>>>>>>> 15f076e949e5808e9b4a1be72833fe429e1dab17
